version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg
    environment:
      POSTGRES_PASSWORD: lol
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
    driver: local
